### ISSUE TITLE
Permission failure when using this package with multiple users on the same server

### ISSUE THREAD

**Issue by thomasderoo4** [enlightn/security-checker#17]
Hello,

I am using this package through [https://github.com/Jorijn/laravel-security-checker](https://github.com/Jorijn/laravel-security-checker) . When using this package on one server with multiple users(**user1**, **user2**), **user1** is the owner of the file _/tmp/php_security_advisories.json_. So any attempt to run the security checker with **user2** gives me a 'Permission Denied'. 

**user1** works completely as expected. **user2** gets the following error:

> file_put_contents(/tmp/php_security_advisories.json): failed to open stream: Permission denied.
> vendor/enlightn/security-checker/src/AdvisoryFetcher.php:138

Possible solution: Maybe the library on **user1** could delete the files when its done with them, so **user2** can put the required files there when it needs to.

Best regards,
Thomas

**Comment by paras-malhotra** [comment]
@thomasderoo4, unfortunately 2 users are currently not supported. The default umask is 0022 which means the dir/file permissions would be 755/644. So, write permissions won't be available to user 2 with the default permissions setup.

I think it would be useful to have a `--temp-dir` option to explicitly specify the temp directory while running the command and also a `--no-cache` option to skip caching. Of course, since you're using the other package, we'd probably have to make changes in that one as well.

I'll mark this as an enhancement to-do. You're welcome to submit a PR on this. Otherwise, I'll try and take a go at it sometime this week.

**Comment by thomasderoo4** [comment]
Hi Paras, thanks for your quick response. 

I feel a temp-dir option would be the best solution in this case! However, I think the laravel-security-checker uses the 'SecurityChecker' and not the 'SecurityCheckerCommand'. The 'AdvisoryFetcher' already contains a $tempdir constructor argument, maybe expose this same $tempdir argument on the 'SecurityChecker' constructor and pass it on to the 'AdvisoryFetcher', so laravel-security-checker can access it through its config. In addition to, of course, adding the --temp-dir option to the 'SecurityCheckerCommand'. Let me know if you think this would be a viable solution.

I dont create pull requests often so i dont have anything set-up right now, but i would be happy to set-up my git environment and give it a try if you think the above solution is good.

Kind regards

**Comment by paras-malhotra** [comment]
@thomasderoo4, yes that sounds great! Feel free to submit a PR on those lines 👍

**Comment by thomasderoo4** [comment]
Hi Paras, I've created pull request #18 
Let me know if i did everything right, sort of new to this github thing!

Regards
